# Generated by Django 4.0.6 on 2022-07-29 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_skill_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='created_at',
            new_name='created',
        ),
    ]
