# Generated by Django 4.0.6 on 2022-07-30 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_person_max_def'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='passion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.demo'),
        ),
    ]
