# Generated by Django 4.0.6 on 2022-07-30 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_person_passion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='passion',
        ),
        migrations.DeleteModel(
            name='Demo',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
