# Generated by Django 4.0.6 on 2022-08-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_person_passion_delete_demo_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='rolex.jpg', null=True, upload_to=''),
        ),
    ]
