# Generated by Django 4.0.6 on 2022-07-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_tag_reviews_project_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='vote_ratio',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='vote_total',
        ),
        migrations.AddField(
            model_name='project',
            name='vote_ratio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='vote_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
