# Generated by Django 4.0.6 on 2022-07-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_project_featured_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('specialty', models.CharField(max_length=200)),
                ('certification', models.CharField(choices=[('A', 'American Board'), ('B', 'Bachelor')], max_length=30)),
            ],
        ),
    ]
