# Generated by Django 4.0.6 on 2022-07-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='tags',
            field=models.ManyToManyField(blank=True, to='my_app.tag'),
        ),
    ]
