# Generated by Django 4.0.6 on 2022-07-26 12:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_doctor_description_doctor_vote_ratio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
