# Generated by Django 4.0.6 on 2022-07-30 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_person_passion_delete_demo_delete_person'),
        ('my_app', '0011_alter_doctor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='doctor',
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
